In [1]:
from pyscbwrapper import SCB

In [2]:
help(SCB)

Help on class SCB in module pyscbwrapper.scb:

class SCB(builtins.object)
 |  SCB(lang, *args)
 |
 |  Version 0.1.1
 |
 |  Methods defined here:
 |
 |  __init__(self, lang, *args)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  clear_query(self)
 |      Clears the query. Mostly an internal function to use in others.
 |
 |  get_data(self)
 |      Returns the data from the constructed query.
 |
 |  get_query(self)
 |      Returns the current query.
 |
 |  get_url(self)
 |      Returns the url to the current folder.
 |
 |  get_variables(self)
 |      Returns a dictionary of variables and their ranges for the bottom node.
 |
 |  go_down(self, *args)
 |      Goes deeper in the hierarchical metadata structure.
 |
 |  go_up(self, k=1)
 |      Goes k levels up in the hierarchical metadata structure.
 |
 |  info(self)
 |      Returns the metadata associated with the current folder.
 |
 |  set_query(self, **kwargs)
 |      Forms a query from input arguments.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [3]:
scb = SCB('sv')

In [4]:
scb.go_down('BE')
scb.info()

[{'id': 'BE0701', 'type': 'l', 'text': 'Demografisk analys (Demografi)'},
 {'id': 'BE0101', 'type': 'l', 'text': 'Befolkningsstatistik'},
 {'id': 'BE0205',
  'type': 'l',
  'text': 'Tidigare folk- och bostadsräkningar 1960-1990 (FoB)'},
 {'id': 'BE0001', 'type': 'l', 'text': 'Namnstatistik'},
 {'id': 'BE0401', 'type': 'l', 'text': 'Befolkningsframskrivningar'}]

In [5]:
scb.go_down('BE0101')
scb.info()

[{'id': 'BE0101A', 'type': 'l', 'text': 'Folkmängd'},
 {'id': 'BE0101B', 'type': 'l', 'text': 'Medelålder'},
 {'id': 'BE0101C', 'type': 'l', 'text': 'Befolkningstäthet'},
 {'id': 'BE0101D', 'type': 'l', 'text': 'Medelfolkmängd'},
 {'id': 'BE0101E', 'type': 'l', 'text': 'Utrikes födda'},
 {'id': 'BE0101F', 'type': 'l', 'text': 'Utländska medborgare'},
 {'id': 'BE0101G', 'type': 'l', 'text': 'Befolkningsförändringar'},
 {'id': 'BE0101H', 'type': 'l', 'text': 'Födda'},
 {'id': 'BE0101I', 'type': 'l', 'text': 'Döda'},
 {'id': 'BE0101J', 'type': 'l', 'text': 'Flyttningar - inrikes och utrikes'},
 {'id': 'BE0101S', 'type': 'l', 'text': 'Hushåll'},
 {'id': 'BE0101L', 'type': 'l', 'text': 'Gifta, Skilda och Änka/änkling'},
 {'id': 'BE0101N', 'type': 'l', 'text': 'Medborgarskapsbyten'},
 {'id': 'BE0101O', 'type': 'l', 'text': 'Partnerskap'},
 {'id': 'BE0101P', 'type': 'l', 'text': 'Asylsökande'},
 {'id': 'BE0101Q', 'type': 'l', 'text': 'Utländsk/svensk bakgrund'},
 {'id': 'BE0101K', 'type': 'l', 'text': 'Adopterade'},
 {'id': 'BE0101M', 'type': 'l', 'text': 'Cirkulär migration'},
 {'id': 'BE0101X', 'type': 'l', 'text': 'Nyckeltal'},
 {'id': 'BE0101Y', 'type': 'l', 'text': 'DeSo'}]

In [6]:
scb.go_down('BE0101A')
scb.info()

[{'id': 'BefolkningNy',
  'type': 't',
  'text': 'Folkmängden efter region, civilstånd, ålder och kön. År 1968 - 2019',
  'updated': '2020-02-20T09:30:00'},
 {'id': 'BefolkningR1860',
  'type': 't',
  'text': 'Befolkning efter ålder och kön. År 1860 - 2019',
  'updated': '2020-02-20T09:30:00'},
 {'id': 'FolkmangdNov',
  'type': 't',
  'text': 'Folkmängden den 1 november efter region, ålder och kön. År 2002 - 2019',
  'updated': '2019-12-09T09:30:00'},
 {'id': 'FolkmangdDistrikt',
  'type': 't',
  'text': 'Folkmängd per distrikt, landskap, landsdel eller riket efter kön. År 2015 - 2019',
  'updated': '2020-03-19T09:30:00'},
 {'id': 'BefolkManad',
  'type': 't',
  'text': 'Folkmängden per månad efter region, ålder och kön. År 2000M01 - 2020M02',
  'updated': '2020-04-07T09:30:00'}]

In [7]:
scb.go_down('BefolkningR1860')
scb.get_variables()

{'ålder': ['0 år',
  '1 år',
  '2 år',
  '3 år',
  '4 år',
  '5 år',
  '6 år',
  '7 år',
  '8 år',
  '9 år',
  '10 år',
  '11 år',
  '12 år',
  '13 år',
  '14 år',
  '15 år',
  '16 år',
  '17 år',
  '18 år',
  '19 år',
  '20 år',
  '21 år',
  '22 år',
  '23 år',
  '24 år',
  '25 år',
  '26 år',
  '27 år',
  '28 år',
  '29 år',
  '30 år',
  '31 år',
  '32 år',
  '33 år',
  '34 år',
  '35 år',
  '36 år',
  '37 år',
  '38 år',
  '39 år',
  '40 år',
  '41 år',
  '42 år',
  '43 år',
  '44 år',
  '45 år',
  '46 år',
  '47 år',
  '48 år',
  '49 år',
  '50 år',
  '51 år',
  '52 år',
  '53 år',
  '54 år',
  '55 år',
  '56 år',
  '57 år',
  '58 år',
  '59 år',
  '60 år',
  '61 år',
  '62 år',
  '63 år',
  '64 år',
  '65 år',
  '66 år',
  '67 år',
  '68 år',
  '69 år',
  '70 år',
  '71 år',
  '72 år',
  '73 år',
  '74 år',
  '75 år',
  '76 år',
  '77 år',
  '78 år',
  '79 år',
  '80 år',
  '81 år',
  '82 år',
  '83 år',
  '84 år',
  '85 år',
  '86 år',
  '87 år',
  '88 år',
  '89 år',
  '90 år',
  '91 år',
  '92 år',
  '93 år',
  '94 år',
  '95 år',
  '96 år',
  '97 år',
  '98 år',
  '99 år',
  '100+ år',
  'totalt ålder'],
 'kön': ['män', 'kvinnor'],
 'tabellinnehåll': ['Folkmängd'],
 'år': ['1860',
  '1861',
  '1862',
  '1863',
  '1864',
  '1865',
  '1866',
  '1867',
  '1868',
  '1869',
  '1870',
  '1871',
  '1872',
  '1873',
  '1874',
  '1875',
  '1876',
  '1877',
  '1878',
  '1879',
  '1880',
  '1881',
  '1882',
  '1883',
  '1884',
  '1885',
  '1886',
  '1887',
  '1888',
  '1889',
  '1890',
  '1891',
  '1892',
  '1893',
  '1894',
  '1895',
  '1896',
  '1897',
  '1898',
  '1899',
  '1900',
  '1901',
  '1902',
  '1903',
  '1904',
  '1905',
  '1906',
  '1907',
  '1908',
  '1909',
  '1910',
  '1911',
  '1912',
  '1913',
  '1914',
  '1915',
  '1916',
  '1917',
  '1918',
  '1919',
  '1920',
  '1921',
  '1922',
  '1923',
  '1924',
  '1925',
  '1926',
  '1927',
  '1928',
  '1929',
  '1930',
  '1931',
  '1932',
  '1933',
  '1934',
  '1935',
  '1936',
  '1937',
  '1938',
  '1939',
  '1940',
  '1941',
  '1942',
  '1943',
  '1944',
  '1945',
  '1946',
  '1947',
  '1948',
  '1949',
  '1950',
  '1951',
  '1952',
  '1953',
  '1954',
  '1955',
  '1956',
  '1957',
  '1958',
  '1959',
  '1960',
  '1961',
  '1962',
  '1963',
  '1964',
  '1965',
  '1966',
  '1967',
  '1968',
  '1969',
  '1970',
  '1971',
  '1972',
  '1973',
  '1974',
  '1975',
  '1976',
  '1977',
  '1978',
  '1979',
  '1980',
  '1981',
  '1982',
  '1983',
  '1984',
  '1985',
  '1986',
  '1987',
  '1988',
  '1989',
  '1990',
  '1991',
  '1992',
  '1993',
  '1994',
  '1995',
  '1996',
  '1997',
  '1998',
  '1999',
  '2000',
  '2001',
  '2002',
  '2003',
  '2004',
  '2005',
  '2006',
  '2007',
  '2008',
  '2009',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019']}

In [8]:
scb.set_query(ålder=scb.get_variables()['ålder'],
              kön=scb.get_variables()['kön'],
              tabellinnehåll=["Folkmängd"], 
              år=["2019"])
scb.get_query()

{'query': [{'code': 'Alder',
   'selection': {'filter': 'item',
    'values': ['0',
     '1',
     '2',
     '3',
     '4',
     '5',
     '6',
     '7',
     '8',
     '9',
     '10',
     '11',
     '12',
     '13',
     '14',
     '15',
     '16',
     '17',
     '18',
     '19',
     '20',
     '21',
     '22',
     '23',
     '24',
     '25',
     '26',
     '27',
     '28',
     '29',
     '30',
     '31',
     '32',
     '33',
     '34',
     '35',
     '36',
     '37',
     '38',
     '39',
     '40',
     '41',
     '42',
     '43',
     '44',
     '45',
     '46',
     '47',
     '48',
     '49',
     '50',
     '51',
     '52',
     '53',
     '54',
     '55',
     '56',
     '57',
     '58',
     '59',
     '60',
     '61',
     '62',
     '63',
     '64',
     '65',
     '66',
     '67',
     '68',
     '69',
     '70',
     '71',
     '72',
     '73',
     '74',
     '75',
     '76',
     '77',
     '78',
     '79',
     '80',
     '81',
     '82',
     '83',
     '84',
     '85',
     '86',
     '87',
     '88',
     '89',
     '90',
     '91',
     '92',
     '93',
     '94',
     '95',
     '96',
     '97',
     '98',
     '99',
     '100+',
     'tot']}},
  {'code': 'Kon', 'selection': {'filter': 'item', 'values': ['1', '2']}},
  {'code': 'ContentsCode',
   'selection': {'filter': 'item', 'values': ['BE0101C£']}},
  {'code': 'Tid', 'selection': {'filter': 'item', 'values': ['2019']}}],
 'response': {'format': 'json'}}

In [9]:
scb.get_url()

'http://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__BE__BE0101__BE0101A/BefolkningR1860'

In [10]:
data = scb.get_data()['data']
data

[{'key': ['0', '1', '2019'], 'values': ['59476']},
 {'key': ['0', '2', '2019'], 'values': ['55907']},
 {'key': ['1', '1', '2019'], 'values': ['60993']},
 {'key': ['1', '2', '2019'], 'values': ['57783']},
 {'key': ['2', '1', '2019'], 'values': ['61598']},
 {'key': ['2', '2', '2019'], 'values': ['58432']},
 {'key': ['3', '1', '2019'], 'values': ['63965']},
 {'key': ['3', '2', '2019'], 'values': ['60716']},
 {'key': ['4', '1', '2019'], 'values': ['63535']},
 {'key': ['4', '2', '2019'], 'values': ['59313']},
 {'key': ['5', '1', '2019'], 'values': ['64161']},
 {'key': ['5', '2', '2019'], 'values': ['60408']},
 {'key': ['6', '1', '2019'], 'values': ['63519']},
 {'key': ['6', '2', '2019'], 'values': ['59816']},
 {'key': ['7', '1', '2019'], 'values': ['63972']},
 {'key': ['7', '2', '2019'], 'values': ['60569']},
 {'key': ['8', '1', '2019'], 'values': ['63414']},
 {'key': ['8', '2', '2019'], 'values': ['60057']},
 {'key': ['9', '1', '2019'], 'values': ['65919']},
 {'key': ['9', '2', '2019'], 'values': ['62249']},
 {'key': ['10', '1', '2019'], 'values': ['64233']},
 {'key': ['10', '2', '2019'], 'values': ['60664']},
 {'key': ['11', '1', '2019'], 'values': ['63762']},
 {'key': ['11', '2', '2019'], 'values': ['59892']},
 {'key': ['12', '1', '2019'], 'values': ['62750']},
 {'key': ['12', '2', '2019'], 'values': ['59155']},
 {'key': ['13', '1', '2019'], 'values': ['62344']},
 {'key': ['13', '2', '2019'], 'values': ['58855']},
 {'key': ['14', '1', '2019'], 'values': ['60263']},
 {'key': ['14', '2', '2019'], 'values': ['57101']},
 {'key': ['15', '1', '2019'], 'values': ['60386']},
 {'key': ['15', '2', '2019'], 'values': ['56558']},
 {'key': ['16', '1', '2019'], 'values': ['59498']},
 {'key': ['16', '2', '2019'], 'values': ['56025']},
 {'key': ['17', '1', '2019'], 'values': ['58491']},
 {'key': ['17', '2', '2019'], 'values': ['54729']},
 {'key': ['18', '1', '2019'], 'values': ['57736']},
 {'key': ['18', '2', '2019'], 'values': ['52590']},
 {'key': ['19', '1', '2019'], 'values': ['59961']},
 {'key': ['19', '2', '2019'], 'values': ['52935']},
 {'key': ['20', '1', '2019'], 'values': ['64376']},
 {'key': ['20', '2', '2019'], 'values': ['52239']},
 {'key': ['21', '1', '2019'], 'values': ['60503']},
 {'key': ['21', '2', '2019'], 'values': ['52627']},
 {'key': ['22', '1', '2019'], 'values': ['58489']},
 {'key': ['22', '2', '2019'], 'values': ['53806']},
 {'key': ['23', '1', '2019'], 'values': ['61097']},
 {'key': ['23', '2', '2019'], 'values': ['57084']},
 {'key': ['24', '1', '2019'], 'values': ['66159']},
 {'key': ['24', '2', '2019'], 'values': ['61319']},
 {'key': ['25', '1', '2019'], 'values': ['70492']},
 {'key': ['25', '2', '2019'], 'values': ['66703']},
 {'key': ['26', '1', '2019'], 'values': ['73547']},
 {'key': ['26', '2', '2019'], 'values': ['69686']},
 {'key': ['27', '1', '2019'], 'values': ['76966']},
 {'key': ['27', '2', '2019'], 'values': ['72657']},
 {'key': ['28', '1', '2019'], 'values': ['78952']},
 {'key': ['28', '2', '2019'], 'values': ['74405']},
 {'key': ['29', '1', '2019'], 'values': ['80028']},
 {'key': ['29', '2', '2019'], 'values': ['76260']},
 {'key': ['30', '1', '2019'], 'values': ['76764']},
 {'key': ['30', '2', '2019'], 'values': ['73098']},
 {'key': ['31', '1', '2019'], 'values': ['75932']},
 {'key': ['31', '2', '2019'], 'values': ['71947']},
 {'key': ['32', '1', '2019'], 'values': ['71904']},
 {'key': ['32', '2', '2019'], 'values': ['69262']},
 {'key': ['33', '1', '2019'], 'values': ['71858']},
 {'key': ['33', '2', '2019'], 'values': ['68001']},
 {'key': ['34', '1', '2019'], 'values': ['70723']},
 {'key': ['34', '2', '2019'], 'values': ['66402']},
 {'key': ['35', '1', '2019'], 'values': ['68333']},
 {'key': ['35', '2', '2019'], 'values': ['64208']},
 {'key': ['36', '1', '2019'], 'values': ['66506']},
 {'key': ['36', '2', '2019'], 'values': ['62870']},
 {'key': ['37', '1', '2019'], 'values': ['66725']},
 {'key': ['37', '2', '2019'], 'values': ['62884']},
 {'key': ['38', '1', '2019'], 'values': ['65114']},
 {'key': ['38', '2', '2019'], 'values': ['62423']},
 {'key': ['39', '1', '2019'], 'values': ['67217']},
 {'key': ['39', '2', '2019'], 'values': ['64318']},
 {'key': ['40', '1', '2019'], 'values': ['65148']},
 {'key': ['40', '2', '2019'], 'values': ['62291']},
 {'key': ['41', '1', '2019'], 'values': ['62908']},
 {'key': ['41', '2', '2019'], 'values': ['60497']},
 {'key': ['42', '1', '2019'], 'values': ['63645']},
 {'key': ['42', '2', '2019'], 'values': ['61100']},
 {'key': ['43', '1', '2019'], 'values': ['64138']},
 {'key': ['43', '2', '2019'], 'values': ['61538']},
 {'key': ['44', '1', '2019'], 'values': ['66103']},
 {'key': ['44', '2', '2019'], 'values': ['63895']},
 {'key': ['45', '1', '2019'], 'values': ['68709']},
 {'key': ['45', '2', '2019'], 'values': ['66563']},
 {'key': ['46', '1', '2019'], 'values': ['67293']},
 {'key': ['46', '2', '2019'], 'values': ['65385']},
 {'key': ['47', '1', '2019'], 'values': ['68359']},
 {'key': ['47', '2', '2019'], 'values': ['66377']},
 {'key': ['48', '1', '2019'], 'values': ['67822']},
 {'key': ['48', '2', '2019'], 'values': ['66105']},
 {'key': ['49', '1', '2019'], 'values': ['66025']},
 {'key': ['49', '2', '2019'], 'values': ['64454']},
 {'key': ['50', '1', '2019'], 'values': ['64919']},
 {'key': ['50', '2', '2019'], 'values': ['63074']},
 {'key': ['51', '1', '2019'], 'values': ['67302']},
 {'key': ['51', '2', '2019'], 'values': ['65592']},
 {'key': ['52', '1', '2019'], 'values': ['70487']},
 {'key': ['52', '2', '2019'], 'values': ['68126']},
 {'key': ['53', '1', '2019'], 'values': ['70875']},
 {'key': ['53', '2', '2019'], 'values': ['68394']},
 {'key': ['54', '1', '2019'], 'values': ['70581']},
 {'key': ['54', '2', '2019'], 'values': ['68405']},
 {'key': ['55', '1', '2019'], 'values': ['69700']},
 {'key': ['55', '2', '2019'], 'values': ['68104']},
 {'key': ['56', '1', '2019'], 'values': ['65138']},
 {'key': ['56', '2', '2019'], 'values': ['62961']},
 {'key': ['57', '1', '2019'], 'values': ['61558']},
 {'key': ['57', '2', '2019'], 'values': ['60205']},
 {'key': ['58', '1', '2019'], 'values': ['59022']},
 {'key': ['58', '2', '2019'], 'values': ['58018']},
 {'key': ['59', '1', '2019'], 'values': ['57933']},
 {'key': ['59', '2', '2019'], 'values': ['57469']},
 {'key': ['60', '1', '2019'], 'values': ['57990']},
 {'key': ['60', '2', '2019'], 'values': ['57024']},
 {'key': ['61', '1', '2019'], 'values': ['57235']},
 {'key': ['61', '2', '2019'], 'values': ['56724']},
 {'key': ['62', '1', '2019'], 'values': ['57169']},
 {'key': ['62', '2', '2019'], 'values': ['57269']},
 {'key': ['63', '1', '2019'], 'values': ['57251']},
 {'key': ['63', '2', '2019'], 'values': ['56590']},
 {'key': ['64', '1', '2019'], 'values': ['55203']},
 {'key': ['64', '2', '2019'], 'values': ['55935']},
 {'key': ['65', '1', '2019'], 'values': ['53745']},
 {'key': ['65', '2', '2019'], 'values': ['54350']},
 {'key': ['66', '1', '2019'], 'values': ['54360']},
 {'key': ['66', '2', '2019'], 'values': ['55150']},
 {'key': ['67', '1', '2019'], 'values': ['53382']},
 {'key': ['67', '2', '2019'], 'values': ['54545']},
 {'key': ['68', '1', '2019'], 'values': ['51846']},
 {'key': ['68', '2', '2019'], 'values': ['53663']},
 {'key': ['69', '1', '2019'], 'values': ['53773']},
 {'key': ['69', '2', '2019'], 'values': ['55234']},
 {'key': ['70', '1', '2019'], 'values': ['54664']},
 {'key': ['70', '2', '2019'], 'values': ['56858']},
 {'key': ['71', '1', '2019'], 'values': ['55463']},
 {'key': ['71', '2', '2019'], 'values': ['58441']},
 {'key': ['72', '1', '2019'], 'values': ['55119']},
 {'key': ['72', '2', '2019'], 'values': ['58022']},
 {'key': ['73', '1', '2019'], 'values': ['54668']},
 {'key': ['73', '2', '2019'], 'values': ['57642']},
 {'key': ['74', '1', '2019'], 'values': ['53480']},
 {'key': ['74', '2', '2019'], 'values': ['56058']},
 {'key': ['75', '1', '2019'], 'values': ['51059']},
 {'key': ['75', '2', '2019'], 'values': ['54018']},
 {'key': ['76', '1', '2019'], 'values': ['46126']},
 {'key': ['76', '2', '2019'], 'values': ['49806']},
 {'key': ['77', '1', '2019'], 'values': ['41314']},
 {'key': ['77', '2', '2019'], 'values': ['44679']},
 {'key': ['78', '1', '2019'], 'values': ['34971']},
 {'key': ['78', '2', '2019'], 'values': ['38796']},
 {'key': ['79', '1', '2019'], 'values': ['31783']},
 {'key': ['79', '2', '2019'], 'values': ['36046']},
 {'key': ['80', '1', '2019'], 'values': ['30052']},
 {'key': ['80', '2', '2019'], 'values': ['35250']},
 {'key': ['81', '1', '2019'], 'values': ['27039']},
 {'key': ['81', '2', '2019'], 'values': ['33085']},
 {'key': ['82', '1', '2019'], 'values': ['24035']},
 {'key': ['82', '2', '2019'], 'values': ['29994']},
 {'key': ['83', '1', '2019'], 'values': ['21536']},
 {'key': ['83', '2', '2019'], 'values': ['27974']},
 {'key': ['84', '1', '2019'], 'values': ['18916']},
 {'key': ['84', '2', '2019'], 'values': ['25169']},
 {'key': ['85', '1', '2019'], 'values': ['16221']},
 {'key': ['85', '2', '2019'], 'values': ['23265']},
 {'key': ['86', '1', '2019'], 'values': ['14397']},
 {'key': ['86', '2', '2019'], 'values': ['21249']},
 {'key': ['87', '1', '2019'], 'values': ['12938']},
 {'key': ['87', '2', '2019'], 'values': ['20111']},
 {'key': ['88', '1', '2019'], 'values': ['11057']},
 {'key': ['88', '2', '2019'], 'values': ['18373']},
 {'key': ['89', '1', '2019'], 'values': ['9376']},
 {'key': ['89', '2', '2019'], 'values': ['16642']},
 {'key': ['90', '1', '2019'], 'values': ['7438']},
 {'key': ['90', '2', '2019'], 'values': ['14012']},
 {'key': ['91', '1', '2019'], 'values': ['6188']},
 {'key': ['91', '2', '2019'], 'values': ['12343']},
 {'key': ['92', '1', '2019'], 'values': ['4694']},
 {'key': ['92', '2', '2019'], 'values': ['10312']},
 {'key': ['93', '1', '2019'], 'values': ['3686']},
 {'key': ['93', '2', '2019'], 'values': ['8433']},
 {'key': ['94', '1', '2019'], 'values': ['2734']},
 {'key': ['94', '2', '2019'], 'values': ['6804']},
 {'key': ['95', '1', '2019'], 'values': ['1956']},
 {'key': ['95', '2', '2019'], 'values': ['5361']},
 {'key': ['96', '1', '2019'], 'values': ['1372']},
 {'key': ['96', '2', '2019'], 'values': ['3869']},
 {'key': ['97', '1', '2019'], 'values': ['917']},
 {'key': ['97', '2', '2019'], 'values': ['2738']},
 {'key': ['98', '1', '2019'], 'values': ['583']},
 {'key': ['98', '2', '2019'], 'values': ['2126']},
 {'key': ['99', '1', '2019'], 'values': ['377']},
 {'key': ['99', '2', '2019'], 'values': ['1477']},
 {'key': ['100+', '1', '2019'], 'values': ['375']},
 {'key': ['100+', '2', '2019'], 'values': ['1832']},
 {'key': ['tot', '1', '2019'], 'values': ['5195814']},
 {'key': ['tot', '2', '2019'], 'values': ['5131775']}]

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame(data)
df['age'] = [k[0] for k in df.key]
df['sex'] = [k[1] for k in df.key]
df['year'] = [int(k[2]) for k in df.key]
df['value'] = [int(k[0]) for k in df['values']]
df

                 key     values   age sex  year    value
0       [0, 1, 2019]    [59476]     0   1  2019    59476
1       [0, 2, 2019]    [55907]     0   2  2019    55907
2       [1, 1, 2019]    [60993]     1   1  2019    60993
3       [1, 2, 2019]    [57783]     1   2  2019    57783
4       [2, 1, 2019]    [61598]     2   1  2019    61598
..               ...        ...   ...  ..   ...      ...
199    [99, 2, 2019]     [1477]    99   2  2019     1477
200  [100+, 1, 2019]      [375]  100+   1  2019      375
201  [100+, 2, 2019]     [1832]  100+   2  2019     1832
202   [tot, 1, 2019]  [5195814]   tot   1  2019  5195814
203   [tot, 2, 2019]  [5131775]   tot   2  2019  5131775

[204 rows x 6 columns]

In [13]:
scb_sex = scb.get_variables()['kön']
df['sex'] = [scb_sex[int(v)-1] for v in df['sex']]

In [14]:
population_2019_by_age = df.loc[:len(df)-3,['age', 'sex', 'value']]

In [15]:
# Bin age data
population_2019_by_age.loc[population_2019_by_age.age == '100+','age'] = 100
population_2019_by_age['age'] = population_2019_by_age['age'].astype(int)

lbls = [f'{v}0-{(v+1)*10-1}' for v in range(10)]
lbls[0] = '0-9'
lbls[-1] = '90+'
population_2019_by_age['agegroup'] = pd.cut(population_2019_by_age['age'], 10, precision=3, labels=lbls)

In [16]:
population_2019_by_age.to_pickle('pop_2019.pkl')

# For reference

In [ ]:
# pop_agegroup = pd.DataFrame(population_2019_by_age.groupby('agegroup')['value'].sum())
# pop_sex = df.loc[202:203, ['sex', 'value']]
# population_2019_by_age.groupby('sex')['value'].sum()

In [17]:
# pop_agegroup.to_pickle('pop_age.pkl')
# pop_sex.to_pickle('pop_sex.pkl')